# Generated by Django 4.2.3 on 2023-07-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('manufacturer', models.TextField()),
                ('equipment', models.TextField()),
                ('type', models.TextField(choices=[('sp', 'Запасная часть'), ('c', 'Расходный материал'), ('lo', 'Масла смазки')], default='sp')),
                ('name', models.TextField()),
                ('SAP_number', models.TextField()),
                ('serial_number', models.TextField()),
                ('storage', models.TextField()),
                ('unit', models.TextField()),
                ('delivery_time', models.FloatField()),
                ('using_time', models.FloatField()),
                ('downtime', models.FloatField()),
                ('delivery_time_and_coefficient', models.FloatField()),
                ('using_in_workshop', models.FloatField()),
                ('price_in_rubles', models.FloatField()),
                ('count', models.FloatField()),
                ('min_fact', models.FloatField()),
                ('max_fact', models.FloatField()),
                ('picture', models.FileField(default=None, null=True, upload_to='images/', verbose_name='Image')),
            ],
        ),
    ]
