# Generated by Django 4.2.3 on 2023-07-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='SAP_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='count',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='delivery_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='delivery_time_and_coefficient',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='downtime',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='equipment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='manufacturer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='max_fact',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='min_fact',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='price_in_rubles',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='serial_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='storage',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.TextField(choices=[('sp', 'Запасная часть'), ('c', 'Расходный материал'), ('lo', 'Масла смазки')], default='sp', null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='unit',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='using_in_workshop',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='using_time',
            field=models.FloatField(null=True),
        ),
    ]
