# Generated by Django 4.2.3 on 2023-07-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_element_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='analog',
            field=models.TextField(default='Нет', null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='ordered',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='picture',
            field=models.TextField(default=None, null=True),
        ),
    ]
