# Generated by Django 4.2.3 on 2023-07-09 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_element_analog_element_ordered_alter_element_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.TextField(choices=[('sp', 'Запасная часть'), ('c', 'Расходный материал'), ('lo', 'Масла смазки')], default='sp', null=None),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('login', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('added_elements', models.ManyToManyField(through='db.Data', to='db.element')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='added_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.element'),
        ),
        migrations.AddField(
            model_name='data',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.user'),
        ),
    ]
