# Generated by Django 4.2.3 on 2023-07-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_data_alter_element_type_user_data_added_element_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.TextField(choices=[('u', 'Пользователь'), ('m', 'Руководитель')], default='u'),
        ),
    ]
