# Generated by Django 4.2.3 on 2023-07-10 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_user_added_elements_data_changings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count_changings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('count_changing', models.FloatField()),
                ('changed_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.element')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='data_changing_elements',
        ),
        migrations.DeleteModel(
            name='Data_changings',
        ),
        migrations.AddField(
            model_name='count_changings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='count_changing_elements',
            field=models.ManyToManyField(related_name='count_changing_elements', through='db.Count_changings', to='db.element'),
        ),
    ]
