# Generated by Django 4.2.3 on 2023-07-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_count_changings_remove_user_data_changing_elements_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Added',
        ),
    ]
