# Generated by Django 4.2.3 on 2023-07-10 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_rename_data_added'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Added',
            new_name='Addings',
        ),
    ]
