# Generated by Django 4.2.3 on 2023-07-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_rename_added_addings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='picture',
            new_name='image',
        ),
    ]
